# Name of the action 
name: Build, Verify, and Push Docker Image

# A trigger for when this action will run
on:
  [workflow_dispatch]

jobs:
  publish_images:
    # runs on a ubuntu vm provided by github
    runs-on: ubuntu-latest
    # each step the job completes
    # it can run commands, run setup taks, run an action, etc
    steps:
      # the name of the first step
      - name: checkout
        # reference the major version of a release
        uses: actions/checkout@v4
      # the name of the second step
      - name: build image
        # build the docker image
        run: |
          docker build . -t langbledsoe/docker-exercise:latest
          docker run -d -p 80:80 langbledsoe/docker-exercise:latest
          sleep 15
  
  # endpoint tests provided by Liatrio
  build:
    runs-on: ubuntu-latest
    # publish_images needs to finish first
    needs: [publish_images]
    steps:
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
      # the name of the third step
      
  push_to_hub:
    runs-on: ubuntu-latest
    # publish_images and build need to finish first
    needs: [publish_images, build]
    # the rest of this job will only run if the other two jobs succeeded
    if: success()
    steps:
      - name: push image to docker hub
        # login to docker hub (using secret) and push the image
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u langbledsoe --password-stdin
          docker push langbledsoe/docker-exercise:latest