  name: Build, Verify, and Push Docker Image

  # A trigger for when this action will run
  on:  
    push:   
      branches:   
        - main  

  jobs:
    one-big-job:
      # runs on a ubuntu vm provided by github
      runs-on: ubuntu-latest
      
      steps:
        # Downloads the repo onto the vm
        - name: checkout repo
          uses: actions/checkout@v4

        # build the docker image and container 
        - name: build image and run container
          run: |
            docker build . -t langbledsoe/docker-exercise:latest
            docker run -d -p 80:80 langbledsoe/docker-exercise:latest 

        # Specific SHA for the commit before the broken test was introduced:
        - name: run tests
          uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

        - name: push image to docker hub
          if: success()
          run: |
            echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u langbledsoe --password-stdin
            docker push langbledsoe/docker-exercise:latest 